name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: docker build -t dtissot/my-resume:latest .

      - name: Log in to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        run: docker push dtissot/my-resume:latest

      - name: Clean up
        run: rm /home/runner/.docker/config.json
